### ISSUE TITLE
error

### ISSUE THREAD

**Issue by emadPirayesh** [tapsellorg/TapsellSDK-AndroidSample#1]
salam az sdk jadid estefade mikonam toy bazi goshiha javab mide toye lg l90 tabligh nemiyad 
toye loge android studio ba 2 ta error ba tage tapsell movajeh misham

02-15 11:03:52.460 19709-19709/? E/Tapsell: Ad is cached and valid! returning to listener
02-15 11:04:23.302 19709-19709/? E/Tapsell: Showing ad no/data
![dddds](https://cloud.githubusercontent.com/assets/25787919/22964640/eb2771ae-f36e-11e6-8084-703a0ac5aea1.png)

02-15 11:04:23.708 19709-24047/? E/Tapsell: suitable ad not found! :(

**Comment by hermamitr** [comment]
سلام.
باگ گزارش شده برطرف شد. از نسخه جدید استفاده کنید.
https://answers.tapsell.ir/?page_id=65

**Comment by emadPirayesh** [comment]
سلام با تشکر ولی هنوز باگ رفع نشده من sdk رو به 3.0.11 تغییر دادم اما هنوز
دارم همون ارور ها رو میبنیم روی بعضی گوشی ها همه چی اوکیه اما روی lg l90 و
samsung tab a ارور میگیره  [image: Inline image 2][image: Inline image
1][image:
Inline image 1]

**Comment by emadPirayesh** [comment]
[image: Inline image 1]

2017-02-18 9:36 GMT+03:30 emad pirayesh <pirayesh.emad@gmail.com>:

**Comment by hermamitr** [comment]
سلام.

لطفا ورودی های خود  شامل 
package name
app key
zone id
را با آنچه در پنل تپسل ثبت کرده اید چک کنید
این ایراد زمان عدم همخوانی اطلاعات اپ با اطلاعات ثبت شده در پنل تپسل رخ می دهد.
