### ISSUE TITLE
در بنر آنی onRewardedAd() کارنکردن

### ISSUE THREAD

**Issue by MohsenRostamzadeh** [tapsellorg/TapsellSDK-AndroidSample#14]
کار نمی کند `onRewardedAd()`در بنر آنی متود
**.ممنون میشم هرچه زودتر این مشکل رو رفع کنید**

**Comment by behdad222** [comment]
نباید کار کنه
OnRewarded برای تبلیغات جایزه‌ای هست نه آنی
