### ISSUE TITLE
E/MediaPlayer: error (-38, 0)

### ISSUE THREAD

**Issue by amin1985** [tapsellorg/TapsellSDK-AndroidSample#2]
سلام
من نسخه 
3.0.20.aar
رو دانلود و به پروژم اضافه کردم در حالتي که ويديو هم نما رو در لايه اصلي برنامه بگذارم ويديو  را با تاچ صفحه نمايش ميده اما اگر همين رو داخل ريسايکلر ويو بسازم موقع نمايش ارور زير رو ميده

05-16 11:26:27.526 17477-17562/amin.co E/Tapsell: onSuccess Golabi
05-16 11:26:27.596 17477-17477/amin.co E/MediaPlayer: start called in state 1, mPlayer(0x0)
05-16 11:26:27.596 17477-17477/amin.co E/MediaPlayer: error (-38, 0)
05-16 11:26:27.596 17477-17477/amin.co E/Tapsell: Player started
05-16 11:26:27.668 17477-17477/amin.co E/MediaPlayer: Error (-38,0)

و ويديو در فريم اول مي مونه اگر روي ويديو دابل کليک کنم شروع به پخش ميکنه اما خودکار پخش نميشه
و اين که در حالت اول با  کليک ويديو تمام صفحه نمايش ميده اما وقتي در ريسايکلر ويو هست به حالت 
fullscreen
 نميره
 
کد هم عين کد هاي نمونه در سايت هست و موقع طراحي لايه شخصي سازي شده ارور زير رو ميده
The following classes could not be instantiated:
- ir.tapsell.sdk.nativeads.views.RateStarView (Open Class, Show Exception, Clear Cache)
- ir.tapsell.sdk.nativeads.views.videoplayer.VideoContainer (Open Class, Show Exception, Clear Cache)
هر چند در برنامه نشون داده ميشن
با لایه های پیشفرض هم همین مشکلات هست

android studio 2.3.1
gradle 3.3
android plugin version 2.3.1
   compileSdkVersion 25
   buildToolsVersion '25.0.3'
 minSdkVersion 14
  targetSdkVersion 25

**Comment by behdad222** [comment]
در نسخه‌های جدیدتر sdk مشکل برطرف شده
