### ISSUE TITLE
این کتابخانه تو مد R8 کلا کار نمیکنه که و اپ کرش میکنه

### ISSUE THREAD

**Issue by DanialV** [tapsellorg/TapsellSDK-AndroidSample#20]
<div dir=rtl>
این کتابخانه کلا با مود R8 کار نمیکنه که از گرادل 3.8 به بعد R8 به صورت دیفالت فعال هستش و دیگه از proguard استفاده نمیشه لطفا هرچه سریعتر مشکل برطرف کنید مرسی.
</div>

**Comment by rasool000** [comment]
واس من کرش نکرد

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
نسخه‌ی آخر با R8 مشکلی نداره

</div>
