### ISSUE TITLE
مشکل در تبلیغات همسان

### ISSUE THREAD

**Issue by SeyedJavadMajidi** [tapsellorg/TapsellSDK-AndroidSample#31]
سلام وقت بخیر
من در نمایش تبلیعات همسان مشکل دارم
لازم به ذکر هست که من قبلا راحت تبلیغات رو نشون میدادم ولی با بروزرسانی پروژم و البته کتابخانه تپسل بشدت به مشکل خوردم
مشکل که به من میگیره و کلا برنامه متوقف میشه در هنگام درخواست تبلیغ همسان هست یعنی این خط
TapsellNativeBannerManager.getAd

اطلاعات پروژم:
compileSdkVersion 30
buildToolsVersion '30.0.3'
minSdkVersion 18
targetSdkVersion 30

کتابخانه:
implementation 'ir.tapsell.sdk:tapsell-sdk-android:4.7.0'

ممنون میشم راهنمایی کنین
با تشکر

**Comment by SeyedJavadMajidi** [comment]
راستی روی getAd توی پروژم خط کشیده شده!
چرا؟
انگار نامعتبر هست یا منسوخ شده!

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

لطفا مطابق [سمپل ](https://github.com/tapsellorg/TapsellSDK-AndroidSample)و داکیومنت از APIها استفاده کنید

</div>
