### ISSUE TITLE
Crash on TapsellPlus.ShowInterstitialAd()

### ISSUE THREAD

**Issue by mossssi** [tapsellorg/TapsellSDK-AndroidSample#32]
com.company.name I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
com.company.name W/ResourceType: Failure getting entry for 0x7f130530 (t=18 e=1328) (error -2147483647)
com.company.name W/cr_media: Requires BLUETOOTH permission
com.company.name E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)

Any comment here?

**Comment by mahdi-malv** [comment]
Tapsell plus issue. I think it's related to [this ](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2020/issues/5) issue.
Please continue the process in that issue if the problem still exists.
