### ISSUE TITLE
Failed to resolve: recyclerview-v7

### ISSUE THREAD

**Issue by OmidMahmoudi** [tapsellorg/TapsellSDK-AndroidSample#4]
سلام بعد دانلود کردنش ساین کردم ُ وی پی انم وصله ولی ارور زیر رو میده.

![screenshot from 2018-08-16 13-02-06](https://user-images.githubusercontent.com/19889603/44197689-9beb1600-a154-11e8-8b19-d6f8aad19c43.png)

**Comment by farzadnone** [comment]
proxy set kardi http+https?

**Comment by OmidMahmoudi** [comment]
پروکسی چی؟گرایدل منظورتونه یا آندروید آستودیو؟
پروکسی ست نکردم 
از VPN استفاده میکنم

**Comment by OmidMahmoudi** [comment]
این خط رو غیر فعال کردم درست شد!
implementation 'com.android.support:recyclerview-v7:27.1.1'

![screenshot from 2018-08-18 10-20-29](https://user-images.githubusercontent.com/19889603/44296267-679c6480-a2d0-11e8-98e4-38e6ed39a4c3.png)
