### ISSUE TITLE
Click events on native banner

### ISSUE THREAD

**Issue by vahid-m** [tapsellorg/TapsellSDK-AndroidSample#5]
As I know the click events are handled **inside the SDK** and we cannot find out that **when the ads are clicked**. As a result,  if we need it for some reason, i.e. to gather analytics data from ads click,  its not possible at this time.
please consider adding an interface to TapsellNativeBannerManager builder class to send out the click events to the parent class.

**Comment by behdad222** [comment]
Unfortunately this is not possible.
