### ISSUE TITLE
Failed to resolve: com.google.android.gms:play-services-ads-identifier:16.0.0 

### ISSUE THREAD

**Issue by snip77** [tapsellorg/TapsellSDK-AndroidSample#7]
مشکل 
Failed to resolve: com.google.android.gms:play-services-ads-identifier:16.0.0 
در نصب نسخه
ir.tapsell.sdk:tapsell-sdk-android:4.3.3
در نسخه 4.1.0 همچین مشکلی نیست

**Comment by behdad222** [comment]
سلام
بله در نسخه جدید به این کتابخونه نیاز داریم
اگر از `androidX` استفاده میکنید این خط رو به فایل `gradle` اضافه کنید
`implementation   'com.google.android.gms:play-services-ads-identifier:17.0.0'`

اگر از `androidx` استفاده نمیکنید در فایل `gradle` اصلی پروژه `google()` رو بیارید زیر `jcenter()`
امیدوارم مشکلتون حل شه

**Comment by snip77** [comment]
متاسفانه درست نشد با ارور زیر مواجه شدم:

`Failed to resolve: com.google.android.gms:play-services-ads-identifier:17.0.0`

**Comment by behdad222** [comment]
مشکل فیلتر شکن ندارید؟

**Comment by snip77** [comment]
ن با سایفون هستش!

**Comment by behdad222** [comment]
با fod چک کنید
https://github.com/freedomofdevelopers/fod

**Comment by snip77** [comment]
با تشکر.چک میکنم ببینم درست میشه یا ن

**Comment by snip77** [comment]
مشکل از اینترنت بود.با سایفون زدم درست شد با دیتا گوشی
مرسی از راهماییتون

**Comment by amirhossein320** [comment]
> سلام
> بله در نسخه جدید به این کتابخونه نیاز داریم
> اگر از `androidX` استفاده میکنید این خط رو به فایل `gradle` اضافه کنید
> `implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'`
> 
> اگر از `androidx` استفاده نمیکنید در فایل `gradle` اصلی پروژه `google()` رو بیارید زیر `jcenter()`
> امیدوارم مشکلتون حل شه







**من  همون مشکل دوستمون رو دارم
وختی از این راهنمایی مشا استفاده میکنم  با ارور زیر مواجه میشم.**

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find play-services-ads-identifier.jar (com.google.android.gms:play-services-ads-identifier:17.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
`

**Comment by behdad222** [comment]
من با تپسل همکاری ندارم

**Comment by MahdiFarzami** [comment]
> > سلام
> > بله در نسخه جدید به این کتابخونه نیاز داریم
> > اگر از `androidX` استفاده میکنید این خط رو به فایل `gradle` اضافه کنید
> > `implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'`
> > اگر از `androidx` استفاده نمیکنید در فایل `gradle` اصلی پروژه `google()` رو بیارید زیر `jcenter()`
> > امیدوارم مشکلتون حل شه
> 
> **من همون مشکل دوستمون رو دارم وختی از این راهنمایی مشا استفاده میکنم با ارور زیر مواجه میشم.**
> 
> `FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:compileDebugKotlin'.
> 
> > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
> > Could not find play-services-ads-identifier.jar (com.google.android.gms:play-services-ads-identifier:17.0.0).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 19s
> `

من هم همين مشکل دارم و با فیلتر شکن های مختلف و FOD هم تست کردم ولی حل نشد.
