### ISSUE TITLE
نمایش تبلیغ با exoplayer

### ISSUE THREAD

**Issue by davod56** [tapsellorg/TapsellSDK-AndroidSample#9]
سلام. می خواستم بدونم چطور می تونم تبلیغات رو با (exoplayer) نمایش بدم.

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
بابت تاخیر در پاسخ‌گویی صمیمانه عذرخواهی می‌کنم.
امکان نماشی تبلیغ در اگزوپلیر تنها برای [تبلیغات وست ما](https://docs.tapsell.ir/tapsell-sdk/android/vast/) وجود دارد.
